### ISSUE TITLE
Replace Inquirer by something else?

### ISSUE THREAD

**Issue by lfilho** [free-time/freetime-cli#11]
Hey man, I'm trying to make contributions to your repo easier by using Docker containers, but Inquirer.js seems no to play nice with them. 

In fact it does work on many shells, includind windows ones, Git Bash for instance. Check their repo and you'll see how many issues they have on that matter...

Could you please:
1) Try and get rid of Inquirer.js?
2) Update the dependencies versions?

**Comment by lfilho** [comment]
Sorry, my bad. I was able to run it.

Updating the dependencies would still be a great thing though

**Comment by fdaciuk** [comment]
@lfilho thanks for the feedback :D 

Inquirer was updated :)
