### ISSUE TITLE
Error in Mac OSX

### ISSUE THREAD

**Issue by matheuswd** [free-time/freetime-cli#14]
When I run `freetime` in the command line, I get this error: 

`/usr/local/lib/node_modules/freetime-cli/lib/freetime-cli.js:4`
`let fs = require('fs');`
`^^^`
`SyntaxError: Unexpected strict mode reserved word`

Do u know something about this?

**Comment by fdaciuk** [comment]
@matheuswd what is your node version? `freetime-cli` requires Node 4+.
If you already have Node 4+, just update it:

```
npm i -g freetime-cli
```

Let me know if this works to you :)

**Comment by matheuswd** [comment]
I updated and now it's working!

Thanks!

Why don't we write in the README file this requirement `Node 4+`?

If we can use this, just merge it :) Its on PR #16

**Comment by fdaciuk** [comment]
Thanks @matheuswd :D

**Comment by matheuswd** [comment]
I must say thanks @fdaciuk
