### ISSUE TITLE
Manutenção do CLI

### ISSUE THREAD

**Issue by andersoonweb** [free-time/freetime-cli#5]
Falta alguns itens para que o cli funcione perfeitamente.
- Por padrão, todos os títulos das palestras seguem essa ordem: Nome da palestra - nome palestrante.
  Quando é passado isso no essas informações no cli ele faz o replace do - e transforma em um espaço. Está ai o primeiro erro a ser corrigido.
- Categorias agora deve ser trocada pra tag ou tags. 
  Se existir apenas uma tag o cli deve retornar na página de post nessa estrutura. 
  <b>tag: nodejs</b>. 
  Lembrando que nodejs  é a categoria que deve ser passada. 
  Se for mais de uma tag deve retornar em forma de um array e a propriedade deve acrescentar um s, segue o exemplo: 
  <b>tags: [css, performace]</b>.
- Caminhos padrão: 
  <b>Image Path</b> <code>app/image/speakers/</code>
  <b>Path to save</b>: <code>_posts/</code>
- Título não aparece no arquivo. Embora o título seja passado no cli não aparece no arquivo final. Isso é muito importante quando queremos dar uma manutenção em certo arquivos :)

Exemplo do arquivo final:
![screenshot from 2015-10-20 22 39 33](https://cloud.githubusercontent.com/assets/3930770/10625628/7bdf4dc8-777b-11e5-9f7b-08bd6fbd2e97.png)

Deveria ficar assim: 
![screenshot from 2015-10-20 22 40 59](https://cloud.githubusercontent.com/assets/3930770/10625637/ae547878-777b-11e5-864b-e20067a53176.png)

@fdaciuk

**Comment by fdaciuk** [comment]
@andersonweb, as tags não funcionam se sempre forem um array, ainda que só com 1 item, e o título sempre como **tags**?

**Comment by andersoonweb** [comment]
Bom questionamento @fdaciuk ! 
Acabei fazer um alguns teste e sim! Por padrão ele pode vim sempre como arrays não diferencia em nada. Também a propriedade tag pode vim sempre como <b>tags</b>, com o <b>s</b> no final, não está apresentando nenhum conflito. :dancer:

**Comment by fdaciuk** [comment]
Show! Melhor que não precisa ficar fazendo tratamento pra isso ;)
