### ISSUE TITLE
Adicionar speakers

### ISSUE THREAD

**Issue by andersoonweb** [free-time/freetime-cli#9]
O cli precisa seguir o modelo novo de publicações do free time, adicionando a opção <b>speakers</b>. O arquivo gerado ficaria assim:

``` md
layout: post
title:  "JavaScript com Google V8 no servidor"
speakers: Luciano Ramalho
date:   2015-03-31 10:13:00
duration: 58:56 min
tag: nodejs
img: /assets/image/speakers/luciano_ramalho.jpg
link: https://www.youtube.com/watch?v=3Sb36C79xE0
```

Agora, não precisamos mas do nome do palestrante no título, logo, poderia remover o <code>-</code>. O titulo da palestra ficará apenas, sem nenhum adicional.
![screenshot from 2015-10-30 22 40 16](https://cloud.githubusercontent.com/assets/3930770/10861212/67182476-7f57-11e5-95b9-1724ca6fe8e3.png)

Para essa tarefa eu invoco... @fdaciuk hauehauiehei

**Comment by fdaciuk** [comment]
Done @andersonweb  ;)

**Comment by andersoonweb** [comment]
Valeu @fdaciuk
